name: SERVER distribute

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            sudo git config --global --add safe.directory /home/***/PlayTogether_Server
            sudo git config --global --add safe.directory ~/PlayTogether_Server
            sudo git config --global --add safe.directory ~/PlayTogether_Server/src
            cd PlayTogether_Server/src
            sudo git checkout .
            sudo git pull origin main
            sudo npm install
            pm2 reload all
